### ISSUE TITLE
Add local installation support.

### ISSUE THREAD

**Issue by rashidi77** [amrosolaiman/Light-and-Dark-Wallpapers-for-Gnome-42#1]
In Fedora Silverblue and other immutable distros,  /usr/share/backgrounds directory should be read-only. So you need to install the wallpapers in ~/.local/share/backgrounds directory instead. I don't know where to install the .xml files however, but there should be a way. If you know that, add support to do that in the easy-installer script.

**Comment by amrosolaiman** [comment]
> In Fedora Silverblue and other immutable distros, /usr/share/backgrounds directory should be read-only. So you need to install the wallpapers in ~/.local/share/backgrounds directory instead. I don't know where to install the .xml files however, but there should be a way. If you know that, add support to do that in the easy-installer script.

Do you thing that changing the ownership and permissions of the following folders is safe?

sudo chown yourusername:yourusername -R usr/share/backgrounds/ /usr/share/gnome-background-properties/
sudo chmod g+w -R usr/share/backgrounds /usr/share/gnome-background-properties/

**Comment by amrosolaiman** [comment]
> In Fedora Silverblue and other immutable distros, /usr/share/backgrounds directory should be read-only. So you need to install the wallpapers in ~/.local/share/backgrounds directory instead. I don't know where to install the .xml files however, but there should be a way. If you know that, add support to do that in the easy-installer script.

Do you have access to write permissions to usr/**local**/share/ directory instead? Because gnome should be able to read xml files even from there.

**Comment by rashidi77** [comment]
> Do you have access to write permissions to usr/**local**/share/ directory instead? Because gnome should be able to read xml files even from there.

I have write access inside that directory (using root user). But I don't know if changes inside that directory will be persistent or not.

**Comment by rashidi77** [comment]
> Do you think that changing the ownership and permissions of the following folders is safe?

I don't think it's safe.

**Comment by amrosolaiman** [comment]
> > Do you think that changing the ownership and permissions of the following folders is safe?
> 
> I don't think it's safe.

Ok, so the easiest way is to create $HOME/.local/share/gnome-background-properties/ folder and then place all the xml files in that folder, and place backgrounds in $HOME/.local/share/backgrounds. 
But before that we have to change the directories in the xml files to the new one ($HOME/.local/share/backgrounds) because otherwise gnome will not find the associated backgrounds.

I'll keep that in the to do list!

**Comment by rashidi77** [comment]
> Ok, so the easiest way is to create $HOME/.local/share/gnome-background-properties/ folder and then place all the xml files in that folder, and place backgrounds in $HOME/.local/share/backgrounds.

That's what I was thinking about. Thanks for the support.

**Comment by amrosolaiman** [comment]
> > Ok, so the easiest way is to create $HOME/.local/share/gnome-background-properties/ folder and then place all the xml files in that folder, and place backgrounds in $HOME/.local/share/backgrounds.
> 
> That's what I was thinking about. Thanks for the support.

Now, should be working as you suggested! Please let me now whether it's really working.

**Comment by rashidi77** [comment]
> > > Ok, so the easiest way is to create $HOME/.local/share/gnome-background-properties/ folder and then place all the xml files in that folder, and place backgrounds in $HOME/.local/share/backgrounds.
> > 
> > 
> > That's what I was thinking about. Thanks for the support.
> 
> Now, should be working as you suggested! Please let me now whether it's really working.

I tried it, it seems it doesn't work. Maybe I am missing something.

**Comment by amrosolaiman** [comment]
> > > > Ok, so the easiest way is to create $HOME/.local/share/gnome-background-properties/ folder and then place all the xml files in that folder, and place backgrounds in $HOME/.local/share/backgrounds.
> > > 
> > > 
> > > That's what I was thinking about. Thanks for the support.
> > 
> > 
> > Now, should be working as you suggested! Please let me now whether it's really working.
> 
> I tried it, it seems it doesn't work. Maybe I am missing something. I edited the xml files as you suggested and placed them in the ~/.local/share/gnome-background-properties/ directory.

Sorry, I meant by using the instructions on the main page.
So just open the terminal and run the following command

curl -s "https://raw.githubusercontent.com/amrosolaiman/Light-and-Dark-Wallpapers-for-Gnome-42/main/direct_install.sh" | sudo bash

**Comment by rashidi77** [comment]
> curl -s "https://raw.githubusercontent.com/amrosolaiman/Light-and-Dark-Wallpapers-for-Gnome-42/main/direct_install.sh" | sudo bash
I tried this and it seems it did not work. Maybe I am missing something?

**Comment by amrosolaiman** [comment]
> > curl -s "https://raw.githubusercontent.com/amrosolaiman/Light-and-Dark-Wallpapers-for-Gnome-42/main/direct_install.sh" | sudo bash
> 
> I tried this and it seems it did not work. Maybe I am missing something?


Try to manually remove the folders ~/.local/share/gnome-background-properties/ and  ~/.local/share/backgrounds/ and then run:

curl -s "https://raw.githubusercontent.com/amrosolaiman/Light-and-Dark-Wallpapers-for-Gnome-42/main/direct_install.sh" | bash

The point is that following this procedures it's working properly on my computer.

You are running Gnome 42, right?

**Comment by rashidi77** [comment]
> You are running Gnome 42, right?

Yes

**Comment by rashidi77** [comment]
After manually removing those directories, it worked. Thank you.
